import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/header/Header";
import { Providers } from "@/providers";
import Footer from "@/components/footer/Footer";
import localFont from "next/font/local";


export const metadata: Metadata = {
  title: "Football Big Data",
  description: "Generated by Luís",
};

const biotiff = localFont({
  src: [
    {
      path: 'assets/fonts/Biotif-Regular.woff2',
      style: 'normal',
      weight: 'normal'

    },
    {
      path: 'assets/fonts/Biotif-Bold.woff2',
      style: 'normal',
      weight: 'bold'

    },
    {
      path: 'assets/fonts/Biotif-RegularItalic.woff2',
      style: 'italic',
      weight: 'normal'

    },
    {
      path: 'assets/fonts/Biotif-Book.woff2',
      style: 'normal',
      weight: 'normal'
    },
  ]
})



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`${biotiff.className} text-foreground bg-background text-slate-400 leading-8`}
      >
        <Providers>
          <div className="min-h-screen flex flex-col">
            <Header/>
              <main className="flex-grow">
                {children}
              </main>
            <Footer/>
          </div>
        </Providers>
      </body>
    </html>
  );
}
